// src/constants/dragon-events.js
export const DRAGON_EVENTS = [
  { id: "f1", name: "Inferno Breath", color: "#c53030", turns: 0, target: "all", desc: "Random column takes 2 damage. Destroyed units chain 1 damage to adjacent in same row.", flavor: "\"The dragon did not aim.\"" },
  { id: "f2", name: "Wildfire Spread", color: "#c53030", turns: 2, target: "all", desc: "Units that took damage this turn take +1 burning damage at end of turn.", flavor: "\"The fire did not go out.\"" },
  { id: "f3", name: "Ashen Rain", color: "#c53030", turns: 0, target: "all", desc: "All units lose 1 HP (-2 for Armored/Stone Skin units).", flavor: "\"The sky rained ash.\"" },
  { id: "f4", name: "Shadow of Wings", color: "#c53030", turns: 2, target: "all", desc: "All units -1 attack range. Archers reduced to range 1.", flavor: "\"The sun disappeared.\"" },
  { id: "f5", name: "Dive Bomb", color: "#c53030", turns: 0, target: "all", desc: "Random unit in rows 3-5 takes 3 damage and is stunned.", flavor: "\"Fell like a comet.\"" },
  { id: "f6", name: "Wing Storm", color: "#c53030", turns: 0, target: "all", desc: "All units pushed 1 tile toward own encampment.", flavor: "\"Beating of a thousand wings.\"" },
  { id: "f7", name: "Dragon's Greed", color: "#c53030", turns: 0, target: "all", desc: "Both players lose 2 points. Player with fewer points loses 1 more.", flavor: "\"Hunger for gold.\"" },
  { id: "f8", name: "Hoard Guardian", color: "#c53030", turns: 0, target: "all", desc: "Spawn Hoard Drake (2HP/2ATK) in row 0 and 8. +1 ATK per point (max +3).", flavor: "\"It wanted to be a dragon.\"" },
  { id: "f9", name: "Gold Fever", color: "#c53030", turns: 2, target: "all", desc: "Destroying a unit grants +1 point but 1 damage.", flavor: "\"Gold sang to them.\"" },
  { id: "f10", name: "Dragon's Ire", color: "#c53030", turns: 0, target: "all", desc: "Units with 3+ HP +1 ATK. Units with 2 or less HP take 1 damage.", flavor: "\"Culling the weak.\"" },
  { id: "f11", name: "Scale Armor", color: "#c53030", turns: 0, target: "all", desc: "Rows 0-2 & 6-8 gain Dragon Scale (+1 HP, immune to ≤2 dmg attacks).", flavor: "\"Taken from the corpse.\"" },
  { id: "f12", name: "Rage of the Ancients", color: "#c53030", turns: 1, target: "all", desc: "All units +2 ATK, then -1 HP at end of turn.", flavor: "\"Kindling.\"" },
  { id: "f13", name: "Meteor Storm", color: "#c53030", turns: 0, target: "all", desc: "3 random units take 1 damage. Destroyed units splash 1 damage to adjacent.", flavor: "\"The sky fell.\"" },
  { id: "f14", name: "Cinder Cloud", color: "#c53030", turns: 2, target: "all", desc: "20% miss chance (40% for Archers).", flavor: "\"Visibility was a luxury.\"" },
  { id: "f15", name: "Flame Vortex", color: "#c53030", turns: 0, target: "all", desc: "Random combat zone unit and adjacent take 2 damage. Grows if kills.", flavor: "\"Fire learned to dance.\"" },
  { id: "f16", name: "Dragon Fear", color: "#c53030", turns: 2, target: "all", desc: "All units -1 ATK. Kings and Generals immune.", flavor: "\"The fear of being noticed.\"" },
  { id: "f17", name: "Terror Roar", color: "#c53030", turns: 0, target: "all", desc: "All units cannot attack this turn. Already terrified take 1 damage.", flavor: "\"A promise kept.\"" },
  { id: "f18", name: "Panic Flight", color: "#c53030", turns: 0, target: "all", desc: "All units must move 1 tile toward own base if able.", flavor: "\"To stay was to burn.\"" },
  { id: "f19", name: "Hoard Call", color: "#c53030", turns: 0, target: "all", desc: "Both +1 point. Player with more gives 1 to the other.", flavor: "\"The gold always lied.\"" },
  { id: "f20", name: "Dragon's Bargain", color: "#c53030", turns: 0, target: "all", desc: "Next player chooses: +3 points OR all units +1 ATK.", flavor: "\"The terms were simple.\"" },
  { id: "f21", name: "Curse of Avarice", color: "#c53030", turns: 3, target: "all", desc: "Any points gained this turn are lost at end of turn.", flavor: "\"The gold demanded tribute.\"" },
  { id: "f22", name: "Scorching Blast", color: "#c53030", turns: 0, target: "all", desc: "Random combat zone unit takes 4 damage. Survivor gains Burning.", flavor: "\"Beyond hot.\"" },
  { id: "f23", name: "Breath of the Ancients", color: "#c53030", turns: 0, target: "all", desc: "All 1 HP units destroyed. Others take 1 damage.", flavor: "\"Reminder of what fire was.\"" },
  { id: "f24", name: "Lava Flow", color: "#c53030", turns: 2, target: "all", desc: "Start of turn: 1 damage (2 to armored) in rows 3-5.", flavor: "\"The ground melted.\"" },
  { id: "f25", name: "Strafe Run", color: "#c53030", turns: 0, target: "all", desc: "Random row takes 1 damage (Archers take 2).", flavor: "\"They flew low.\"" },
  { id: "f26", name: "Talons of the Beast", color: "#c53030", turns: 0, target: "all", desc: "Random encampment unit takes 2 damage (King takes 4).", flavor: "\"Collecting.\"" },
  { id: "f27", name: "Aerial Dominance", color: "#c53030", turns: 2, target: "all", desc: "All -1 range. Archers cannot attack.", flavor: "\"The sky belongs to the dragons.\"" },
  { id: "f28", name: "Wyrm's Awakening", color: "#c53030", turns: 0, target: "all", desc: "Spawn Wyrmling (1HP/1ATK, move 2) in row 0 and 8.", flavor: "\"They would be dragons soon.\"" },
  { id: "f29", name: "Elder Dragon's Gaze", color: "#c53030", turns: 1, target: "all", desc: "Attackers take 1 damage. Non-attackers gain +1 HP.", flavor: "\"It judged.\"" },
  { id: "f30", name: "The Age of Fire", color: "#c53030", turns: 0, target: "all", desc: "Fire/Dragon units +3 ATK. Others -1 HP.", flavor: "\"This was a reminder.\"" },
  { id: "f31", name: "Wing Gust", color: "#c53030", turns: 0, target: "all", desc: "All units pushed 1 random direction.", flavor: "\"The battlefield rearranged.\"" },
  { id: "f32", name: "Fire Wall", color: "#c53030", turns: 2, target: "all", desc: "Random row boundary becomes fire wall.", flavor: "\"Burned ambition.\"" },
  { id: "f33", name: "Dragon's Lift", color: "#c53030", turns: 0, target: "all", desc: "Random unit dropped on random empty tile.", flavor: "\"Learn to fly.\"" },
  { id: "f34", name: "Thermal Updraft", color: "#c53030", turns: 2, target: "all", desc: "All pushed toward row 4. Row 4 gains +1 ATK.", flavor: "\"Bodies rose with it.\"" },
  { id: "f35", name: "Burning Ground", color: "#c53030", turns: 3, target: "all", desc: "Rows 3-5 become Burning Ground (1 dmg per turn end).", flavor: "\"The ground remembered.\"" },
  { id: "f36", name: "Smoke Screen", color: "#c53030", turns: 0, target: "all", desc: "Combat zone: -2 to hit. Archers range 0 in smoke.", flavor: "\"From the dragon's breath.\"" },
  { id: "f37", name: "Meteor Impact", color: "#c53030", turns: 0, target: "all", desc: "Random tile meteor strike. Creates crater.", flavor: "\"The sky fell.\"" },
  { id: "f38", name: "Aerial Carry", color: "#c53030", turns: 0, target: "all", desc: "Territory units carried to random tile with Aerial Advantage.", flavor: "\"They saw as dragons see.\"" },
  { id: "f39", name: "Lava Flow", color: "#c53030", turns: 2, target: "all", desc: "Random row becomes lava: 1 dmg + push toward base.", flavor: "\"Everything became ash.\"" },
  { id: "f40", name: "Wind Shear", color: "#c53030", turns: 0, target: "all", desc: "Two random units swap and become Disoriented.", flavor: "\"The wind did not care.\"" }
];

export default DRAGON_EVENTS;
