// src/constants/dwarven-events.js
export const DWARVEN_EVENTS = [
  { id: "d1", name: "Collapsing Tunnel", color: "#744210", turns: 2, target: "all", desc: "All units have -1 movement range. At end of each turn, a random unit takes 1 damage.", flavor: "\"The ancient supports finally gave way. The mountain reclaims what was stolen from it.\"" },
  { id: "d2", name: "Dwarven Deadfall", color: "#744210", turns: 0, target: "all", desc: "Deal 1 damage to all units in rows 3-5. If any destroyed, next player gains 1 point.", flavor: "\"A single tripwire. Centuries of dwarven engineering reduced to a simple, brutal trap.\"" },
  { id: "d3", name: "Pressure Plate", color: "#744210", turns: 1, target: "all", desc: "Any unit that moves 1+ tiles this turn takes 1 damage. Tapped units that move take 2 damage.", flavor: "\"The floor groaned. Then it screamed. Then it swallowed three soldiers whole.\"" },
  { id: "d4", name: "Awakened Sentinel", color: "#744210", turns: 0, target: "all", desc: "Spawn Stone Sentinel (3HP/2ATK, cannot move) in random empty tile in row 0 and row 8.", flavor: "\"The runes flared to life. The statue's eyes opened.\"" },
  { id: "d5", name: "Golem's Grasp", color: "#744210", turns: 0, target: "all", desc: "Random enemy unit is Grappled (cannot move or attack) for 1 turn. Knights or larger take 1 damage.", flavor: "\"Stone fingers closed around the knight's throat.\"" },
  { id: "d6", name: "Ancient Warden", color: "#744210", turns: 2, target: "all", desc: "All units gain +1 max HP. Any unit that attacks loses 1 HP at end of turn.", flavor: "\"The Warden does not choose sides.\"" },
  { id: "d7", name: "Rune of the Forge", color: "#744210", turns: 0, target: "all", desc: "Units in rows 0-2 and 6-8 gain +1 ATK (+2 for Generals and Towers).", flavor: "\"The old forges still burn.\"" },
  { id: "d8", name: "Runic Reversal", color: "#744210", turns: 0, target: "all", desc: "Reverse the most recent non-instant event (if possible).", flavor: "\"The runes do not forget.\"" },
  { id: "d9", name: "Dwarven Armory", color: "#744210", turns: 0, target: "all", desc: "Units in row 0 and 8 gain Armored (+1 HP, -1 movement) until end of next turn.", flavor: "\"If you can't outrun them, outlast them.\"" },
  { id: "d10", name: "Vein of Gold", color: "#744210", turns: 0, target: "all", desc: "Both players gain +2 points. The next player to attack loses 1 point.", flavor: "\"Gold changes hands. Gold changes hearts.\"" },
  { id: "d11", name: "Miner's Strike", color: "#744210", turns: 0, target: "all", desc: "Deal 2 damage to random unit in opponent's encampment. If destroyed, affected player gains 2 points.", flavor: "\"They came for the gold.\"" },
  { id: "d12", name: "Cursed Hoard", color: "#744210", turns: 1, target: "all", desc: "Any unit that destroys another this turn becomes Cursed (-1 ATK, -1 HP).", flavor: "\"The curse was eternal.\"" },
  { id: "d13", name: "Tremor", color: "#744210", turns: 0, target: "all", desc: "All units stunned (no move/attack) for 1 turn. Towers immune.", flavor: "\"The mountain shrugged.\"" },
  { id: "d14", name: "Stone Rain", color: "#744210", turns: 2, target: "all", desc: "At start of each turn, 1 damage to all units in rows 3-5.", flavor: "\"The ceiling became the floor.\"" },
  { id: "d15", name: "Earthen Shield", color: "#744210", turns: 0, target: "all", desc: "Random unit in row 0 and row 8 gains Stone Skin (immune to next 2 attacks ≤2 dmg).", flavor: "\"The mountain protects.\"" },
  { id: "d16", name: "Hall of Echoes", color: "#744210", turns: 2, target: "all", desc: "All units +1 attack range but 20% chance to miss.", flavor: "\"Sound travels strangely here.\"" },
  { id: "d17", name: "Support Failure", color: "#744210", turns: 0, target: "all", desc: "Random column: all units take 1 damage and pushed 1 tile toward base.", flavor: "\"The beam snapped.\"" },
  { id: "d18", name: "Buried Alive", color: "#744210", turns: 0, target: "all", desc: "Random unit in rows 3-5 with ≤2 HP destroyed.", flavor: "\"The mountain closes its fist.\"" },
  { id: "d19", name: "Dwarven Contraption", color: "#744210", turns: 0, target: "all", desc: "Spawn Steam Golem (2HP/3ATK, move 2) in row 0 and 8. Self-destruct after 2 turns.", flavor: "\"The gears still turned.\"" },
  { id: "d20", name: "Rune-Powered Drill", color: "#744210", turns: 0, target: "all", desc: "Random unit in rows 3-5 takes 3 damage. Survivor gains -1 HP permanent.", flavor: "\"It carved through armor.\"" },
  { id: "d21", name: "Ancient Mechanism", color: "#744210", turns: 3, target: "all", desc: "End of each turn: random unit +1 HP or -1 HP (50/50).", flavor: "\"Function only.\"" },
  { id: "d22", name: "Granite Plate", color: "#744210", turns: 0, target: "all", desc: "Rows 0-2 & 6-8: +1 HP and Heavy (-1 move).", flavor: "\"The armor was grown.\"" },
  { id: "d23", name: "Obsidian Edge", color: "#744210", turns: 0, target: "all", desc: "Random unit in rows 0-2 & 6-8: next attack +2 dmg, ignores armor.", flavor: "\"Volcanic glass.\"" },
  { id: "d24", name: "Petrified", color: "#744210", turns: 0, target: "all", desc: "Random combat zone unit Petrified (+3 HP, no move/attack) for 2 turns.", flavor: "\"Watch and suffer.\"" },
  { id: "d25", name: "Miner's Rage", color: "#744210", turns: 0, target: "all", desc: "All Soldiers +2 ATK +1 move this turn, then Exhausted.", flavor: "\"The pickaxe became a weapon.\"" },
  { id: "d26", name: "Tunnel Charge", color: "#744210", turns: 0, target: "all", desc: "Move through enemy units (1 dmg each). Cannot end on occupied tile.", flavor: "\"They went through.\"" },
  { id: "d27", name: "Pickaxe Storm", color: "#744210", turns: 1, target: "all", desc: "Moving units take 1 damage. All attacks deal -1 damage.", flavor: "\"Dust and metal and screams.\"" },
  { id: "d28", name: "Dwarven Ancestor", color: "#744210", turns: 0, target: "all", desc: "Spawn Dwarven Ghost (1HP/2ATK, ethereal) in row 0 and 8.", flavor: "\"They could not rest.\"" },
  { id: "d29", name: "Echo of the Forge", color: "#744210", turns: 2, target: "all", desc: "Armored units +1 ATK. Unarmored units -1 ATK.", flavor: "\"The forge remembered.\"" },
  { id: "d30", name: "The Mountain Remembers", color: "#744210", turns: 0, target: "all", desc: "Units on board 3+ turns: +2 HP +1 ATK. New units take 1 damage.", flavor: "\"The mountain has a long memory.\"" },
  { id: "d31", name: "Tunnel Network", color: "#744210", turns: 0, target: "all", desc: "Create tunnels between row 0 and row 8.", flavor: "\"Heartbeats to cross.\"" },
  { id: "d32", name: "Earthquake Shift", color: "#744210", turns: 0, target: "all", desc: "Random row pushed left or right randomly.", flavor: "\"The mountain shrugged.\"" },
  { id: "d33", name: "Stone Wall", color: "#744210", turns: 2, target: "all", desc: "Random column becomes 5 HP wall.", flavor: "\"The wall rose from the earth.\"" },
  { id: "d34", name: "Dwarven Elevator", color: "#744210", turns: 0, target: "all", desc: "Random unit in row 0/8 teleported randomly in its column.", flavor: "\"Up or down.\"" },
  { id: "d35", name: "Collapsing Floor", color: "#744210", turns: 0, target: "all", desc: "Combat zone units fall 1 row toward their base.", flavor: "\"The floor remembered it was a ceiling.\"" },
  { id: "d36", name: "Rune Portal", color: "#744210", turns: 0, target: "all", desc: "Two random units swap positions.", flavor: "\"Space bent.\"" },
  { id: "d37", name: "Mine Shaft", color: "#744210", turns: 3, target: "all", desc: "Random column becomes instant travel shaft.", flavor: "\"Digging toward each other.\"" },
  { id: "d38", name: "Support Beam", color: "#744210", turns: 0, target: "all", desc: "Random tile reinforced for 3 turns.", flavor: "\"Older than the war.\"" },
  { id: "d39", name: "Dwarven Bridge", color: "#744210", turns: 0, target: "all", desc: "Random column gets bridge over combat zone.", flavor: "\"Bridges over battlefields.\"" },
  { id: "d40", name: "Ancient Mechanism", color: "#744210", turns: 0, target: "all", desc: "Random 3x3 section rotates 90° clockwise.", flavor: "\"It moved armies.\"" }
];

export default DWARVEN_EVENTS;
