// src/constants/highlands-events.js
export const HIGHLANDS_EVENTS = [
  { id: "h1", name: "Highland Charge", color: "#2f855a", turns: 0, target: "all", desc: "Soldiers may charge 2 tiles toward enemy, dealing 1 damage per enemy passed.", flavor: "\"They did not march. They ran.\"" },
  { id: "h2", name: "Warband Assault", color: "#2f855a", turns: 0, target: "all", desc: "Units in own half gain +1 ATK (+2 if in enemy half).", flavor: "\"The war cry was a promise.\"" },
  { id: "h3", name: "Berserker's Fury", color: "#2f855a", turns: 0, target: "all", desc: "Random Soldier +3 ATK this turn (takes 1 damage after).", flavor: "\"The blood sang.\"" },
  { id: "h4", name: "Highland Mist", color: "#2f855a", turns: 2, target: "all", desc: "All units -1 attack range. Archers -2 range.", flavor: "\"The mist swallows arrows.\"" },
  { id: "h5", name: "Fog of War", color: "#2f855a", turns: 0, target: "all", desc: "20% miss chance (40% in combat zone).", flavor: "\"The highlands breathing.\"" },
  { id: "h6", name: "Veil of Ancestors", color: "#2f855a", turns: 0, target: "all", desc: "Units in row 0 and 8 cannot be targeted for 1 turn.", flavor: "\"Ancestors protect.\"" },
  { id: "h7", name: "Blood Oath", color: "#2f855a", turns: 0, target: "all", desc: "Soldiers +1 ATK vs Archers and vice versa (permanent).", flavor: "\"Suffering was an art.\"" },
  { id: "h8", name: "Feud's Reckoning", color: "#2f855a", turns: 0, target: "all", desc: "Random unit that has destroyed another this game takes 3 damage.", flavor: "\"The grudge was patient.\"" },
  { id: "h9", name: "Vendetta", color: "#2f855a", turns: 3, target: "all", desc: "Destroying a unit applies Marked (+1 damage taken).", flavor: "\"Blood called for blood.\"" },
  { id: "h10", name: "Oath of the Stone", color: "#2f855a", turns: 0, target: "all", desc: "Rows 0-2 & 6-8: +1 HP (+2 for King/General).", flavor: "\"The oath was to the land.\"" },
  { id: "h11", name: "Broken Oath", color: "#2f855a", turns: 0, target: "all", desc: "Random armored unit loses protection and takes 2 damage.", flavor: "\"The highlands do not forgive.\"" },
  { id: "h12", name: "Ancestral Pact", color: "#2f855a", turns: 2, target: "all", desc: "Non-moving units +1 ATK. Moving units -1 ATK.", flavor: "\"Stand your ground.\"" },
  { id: "h13", name: "Gale Force", color: "#2f855a", turns: 0, target: "all", desc: "All units pushed 1 random direction.", flavor: "\"The highlands screaming.\"" },
  { id: "h14", name: "Thunderclap", color: "#2f855a", turns: 0, target: "all", desc: "All units stunned 1 turn. Towers immune.", flavor: "\"Men broke.\"" },
  { id: "h15", name: "Storm's Wrath", color: "#2f855a", turns: 2, target: "all", desc: "Start of turn: 1 damage to units that didn't move.", flavor: "\"The storm reminded them.\"" },
  { id: "h16", name: "Battle Roar", color: "#2f855a", turns: 0, target: "all", desc: "Own half +1 ATK (+2 in enemy half).", flavor: "\"This ground is ours.\"" },
  { id: "h17", name: "War Chant", color: "#2f855a", turns: 2, target: "all", desc: "Own half +1 HP per turn start but cannot retreat.", flavor: "\"No retreat.\"" },
  { id: "h18", name: "Scream of the Highlands", color: "#2f855a", turns: 0, target: "all", desc: "All 1 HP units destroyed. Others take 1 damage.", flavor: "\"The land rejecting invaders.\"" },
  { id: "h19", name: "Spirit of the Fallen", color: "#2f855a", turns: 0, target: "all", desc: "Spawn Highland Ghost in row 0 and 8.", flavor: "\"They could not rest.\"" },
  { id: "h20", name: "Ancestor's Blessing", color: "#2f855a", turns: 0, target: "all", desc: "Random encampment unit +2 HP and immune to next negative effect.", flavor: "\"Bloodline will not end.\"" },
  { id: "h21", name: "Ghostly Charge", color: "#2f855a", turns: 0, target: "all", desc: "Move through enemies (1 dmg). Become Spectral.", flavor: "\"Memory is harder to kill.\"" },
  { id: "h22", name: "Highland Ambush", color: "#2f855a", turns: 0, target: "all", desc: "Combat zone units take 2 damage. Kill = next player +1 point.", flavor: "\"They came from the mist.\"" },
  { id: "h23", name: "Flanking Maneuver", color: "#2f855a", turns: 0, target: "all", desc: "Units in column 0 and 8 take 2 damage (3 if on edge).", flavor: "\"Winning means living.\"" },
  { id: "h24", name: "Night Raid", color: "#2f855a", turns: 1, target: "all", desc: "20% miss chance (40% for Archers).", flavor: "\"The night was hungry.\"" },
  { id: "h25", name: "Code of Honor", color: "#2f855a", turns: 0, target: "all", desc: "Attacking units +1 ATK but cannot hit same type twice.", flavor: "\"How you won mattered.\"" },
  { id: "h26", name: "Glory or Death", color: "#2f855a", turns: 0, target: "all", desc: "Own half +1 ATK. Non-attackers -1 HP.", flavor: "\"To not fight was to not exist.\"" },
  { id: "h27", name: "Last Stand", color: "#2f855a", turns: 0, target: "all", desc: "Encampment units +2 HP and Immovable for 2 turns.", flavor: "\"This is where we make our stand.\"" },
  { id: "h28", name: "Call to Arms", color: "#2f855a", turns: 0, target: "all", desc: "Encampment units +1 move +1 ATK. Must advance.", flavor: "\"The pipes commanded.\"" },
  { id: "h29", name: "Lament of the Fallen", color: "#2f855a", turns: 2, target: "all", desc: "Destroying unit loses -1 ATK permanently.", flavor: "\"The pipes played for the dead.\"" },
  { id: "h30", name: "Echoes of Glory", color: "#2f855a", turns: 0, target: "all", desc: "Units 3+ turns old +2 ATK. New units -1 ATK.", flavor: "\"The old ones remembered.\"" },
  { id: "h31", name: "Mist Step", color: "#2f855a", turns: 2, target: "all", desc: "Move through enemies/occupied tiles.", flavor: "\"They became the mist.\"" },
  { id: "h32", name: "War Banner", color: "#2f855a", turns: 3, target: "all", desc: "Random tile banner: friends +1 ATK, enemies -1 ATK.", flavor: "\"The clans followed.\"" },
  { id: "h33", name: "Flanking Route", color: "#2f855a", turns: 0, target: "all", desc: "Territory units teleported to enemy territory with +2 ATK.", flavor: "\"They emerged where least expected.\"" },
  { id: "h34", name: "Bagpipe March", color: "#2f855a", turns: 0, target: "all", desc: "All pushed toward own base. Combat zone +1 ATK.", flavor: "\"By blood.\"" },
  { id: "h35", name: "Ambush Position", color: "#2f855a", turns: 2, target: "all", desc: "Random territory units hidden then revealed with +2 ATK strike.", flavor: "\"The mist hid them.\"" },
  { id: "h36", name: "Storm Front", color: "#2f855a", turns: 0, target: "all", desc: "Combat zone shifts 1 row. Units pushed with it.", flavor: "\"The highlands decided.\"" },
  { id: "h37", name: "Clan Totem", color: "#2f855a", turns: 0, target: "all", desc: "Create totems for instant teleport.", flavor: "\"Wherever you fall, we bring you home.\"" },
  { id: "h38", name: "Mud Trap", color: "#2f855a", turns: 2, target: "all", desc: "Combat zone becomes mud (extra move cost).", flavor: "\"Mud was patient.\"" },
  { id: "h39", name: "Highland Leap", color: "#2f855a", turns: 0, target: "all", desc: "Territory units leap over enemies.", flavor: "\"They flew.\"" },
  { id: "h40", name: "Gale Force", color: "#2f855a", turns: 0, target: "all", desc: "All units pushed random direction. Combat zone +1 ATK.", flavor: "\"The wind carried them forward.\"" }
];

export default HIGHLANDS_EVENTS;
